Add more info about current location
icerockdev/moko-geo pull request #18
Opened 2021-03-27 19:23 UTC by xpathexception

I added some new fields to location report such as azimuth, altitude, speed and timestamp. 

There are some differences in reported values between iOS and Android. For example, accuracy values on iOS can be negative according to https://developer.apple.com/documentation/corelocation/cllocation/1423599-horizontalaccuracy. On the other hand they can't be negative on Android. For now I don't really know if this case should be covered by library itself.

For backward compatibility I decided to add separate flow and container for extended location reports.

2021-03-28 10:43 UTC, Alex009 requested changes

2021-03-28 10:43 UTC, Alex009 commented on geo/src/androidMain/kotlin/dev/icerock/moko/geo/LocationTracker.kt
> +        else lastLocation.verticalAccuracyMeters.toDouble()
i suggest not pass zero, but send null in case where we can't get this data at all

2021-03-28 10:43 UTC, Alex009 commented on geo/src/androidMain/kotlin/dev/icerock/moko/geo/LocationTracker.kt
> +        trackerScope.launch { extendedLocationsChannel.send(extendedLocation) }
why started another launch? whi not pass in one launch each send async?

2021-03-28 10:43 UTC, Alex009 commented on geo/src/commonMain/kotlin/dev/icerock/moko/geo/Altitude.kt
> +package dev.icerock.moko.geo
copyright as in other files required

2021-03-28 10:43 UTC, Alex009 commented on geo/src/commonMain/kotlin/dev/icerock/moko/geo/Azimuth.kt
> +package dev.icerock.moko.geo
copyright as in other files required

2021-03-28 10:43 UTC, Alex009 commented on geo/src/commonMain/kotlin/dev/icerock/moko/geo/ExtendedLocation.kt
> +package dev.icerock.moko.geo
copyright as in other files required

2021-03-28 10:43 UTC, Alex009 commented on geo/src/commonMain/kotlin/dev/icerock/moko/geo/Location.kt
> +package dev.icerock.moko.geo
copyright as in other files required

2021-03-28 10:43 UTC, Alex009 commented on geo/src/commonMain/kotlin/dev/icerock/moko/geo/Speed.kt
> +package dev.icerock.moko.geo
copyright as in other files required

2021-03-28 10:43 UTC, Alex009 commented on geo/src/iosX64Main/kotlin/dev/icerock/moko/geo/Tracker.kt
> +            else location.courseAccuracy
here i suggest nullable value too. in case of unavailable data

2021-03-28 10:43 UTC, Alex009 commented on geo/src/iosX64Main/kotlin/dev/icerock/moko/geo/Tracker.kt
> +            trackerScope.launch { extendedLocationsChannel.send(extendedLocation) }
and here we can use one shared `launch` i think

2021-03-28 16:38 UTC, xpathexception commented
Thanks for the review! I've made all requested changes.

2021-03-29 05:31 UTC, Alex009 approved these changes
thanks for contribution!

2021-03-29 05:31 UTC, merged